import SideRightBar from "./components/SideRightBar";
import Sidebar from "./components/Sidebar";
import DialogProvider from "./context/DialogContext";
import GlobalProvider from "./context/GlobalContext";
import "./globals.css";
import { Inter } from "next/font/google";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-hidden h-full`}>
        <GlobalProvider>
          <DialogProvider>
            <div className="flex h-full">
              <Sidebar />
              <main className="flex-1 overflow-auto">{children}</main>
              <aside className="hidden md:block lg:w-1/4 md:w-1/3 h-screen">
                <SideRightBar />
              </aside>
            </div>
            <ToastContainer autoClose={1000}/>
          </DialogProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}

/*


*/
